name: Fly Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy app
    environment: production
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: |
          flyctl deploy --remote-only --app dms-frontendapp-prod \
            --build-arg NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL }}" \
            --build-arg NEXT_PUBLIC_MAX_FILE_SIZE_MB="25" \
            --build-arg NEXT_PUBLIC_ALLOWED_FILE_TYPES="pdf,doc,docx,xls,xlsx,ppt,pptx,txt,jpg,jpeg,png,gif,csv,json,xml"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
