# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set Fly Secrets
        run: |
          flyctl secrets set \
            NEXT_PUBLIC_API_URL="${{ env.NEXT_PUBLIC_API_URL }}" \
            NEXT_PUBLIC_MAX_FILE_SIZE_MB="${{ env.NEXT_PUBLIC_MAX_FILE_SIZE_MB }}" \
            NEXT_PUBLIC_ALLOWED_FILE_TYPES="${{ env.NEXT_PUBLIC_ALLOWED_FILE_TYPES }}" \
            NODE_ENV="production" \
            --app dms-frontendapp-prod
      - name: Deploy to Fly
        run:  flyctl deploy --remote-only --app dms-frontendapp-prod \
            --build-arg NEXT_PUBLIC_API_URL="${{ env.NEXT_PUBLIC_API_URL }}" \
            --build-arg NEXT_PUBLIC_MAX_FILE_SIZE_MB="${{ env.NEXT_PUBLIC_MAX_FILE_SIZE_MB }}" \
            --build-arg NEXT_PUBLIC_ALLOWED_FILE_TYPES="${{ env.NEXT_PUBLIC_ALLOWED_FILE_TYPES }}"

